
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5437:5432

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  back:
    image: node:22-alpine
    env_file:
      - .env
      - ./back/.env
    volumes:
      - ./back:/app
      - ./bftypes:/app/types
    ports:
      - 3300:3000
    expose:
      - 3300
    working_dir: '/app'
    entrypoint: 'npm run start:dev'

  front:
    image: node:22-alpine
    env_file:
      - .env
      - ./front/.env
    volumes:
      - ./front:/app
      - ./bftypes:/app/types
    ports:
      - 3302:3302
    working_dir: '/app'
    entrypoint: 'npm run dev -- --host'