
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5437:5432

  back:
    image: node:lts-slim
    restart: always
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
      - ./bftypes:/app/types
    ports:
      - 3300:3300
    working_dir: '/app'
    entrypoint: 'npm run start:dev'
